# Logging config for Docker
rootLogger: WARN, console, file

logger:
  # Log action execution errors for easier debugging
  action: WARN

appender:
# configure stdout
  console:
    threshold: ERROR
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
