# Logging config for Docker
rootLogger: INFO, file

logger:
  # Log action execution errors for easier debugging
  action: WARN

appender:
  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
